
sys.path.append(os.path.abspath("."))

import collections, datetime, functools, glob, itertools, json, math, os, os.path, requests, shutil, tempfile, urllib
from pprint import pprint

import numpy as np, pandas as pd
import scipy as sp, scipy.stats

import Bio, Bio.PDB, Bio.SwissProt

wildcard_constraints: # Constrain wildcards to prevent rule ambiguities: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#wildcards
    # Structures: always start with a UniProt id, e.g. P00533_s_3qwq_e7 (SWISS_MODEL) or P00533_model1 (RoseTTAFold)
    struct_pref = r'\w\w/\w\w/\w\w',
    struct_id = r'(\w|-|_)+',
    prev_steps = r'(\w|\.)*?', # zero or more word characters or a dot, minimal match
    base = r'\w+', # base directory

from workflow.modules import *

import resources

include: 'rules/common.smk'

#include: 'rules/fig4ABC.smk'
include: 'rules/af2_bulk.smk'
