
af2_bulk_id: # https://alphafold.ebi.ac.uk/download
# model organism proteomes:
- UP000000437_7955_DANRE_v2
- UP000000559_237561_CANAL_v2
- UP000000589_10090_MOUSE_v2
- UP000000625_83333_ECOLI_v2
- UP000000803_7227_DROME_v2
- UP000000805_243232_METJA_v2
- UP000001940_6239_CAEEL_v2
- UP000002195_44689_DICDI_v2
- UP000002311_559292_YEAST_v2
- UP000002485_284812_SCHPO_v2
- UP000002494_10116_RAT_v2
- UP000005640_9606_HUMAN_v2
- UP000006548_3702_ARATH_v2
- UP000007305_4577_MAIZE_v2
- UP000008827_3847_SOYBN_v2
- UP000059680_39947_ORYSJ_v2
# global health proteomes:
- UP000001631_447093_AJECG_v2
- UP000006672_6279_BRUMA_v2
- UP000000799_192222_CAMJE_v2
- UP000094526_86049_9EURO1_v2
- UP000274756_318479_DRAME_v2
- UP000325664_1352_ENTFC_v2
- UP000053029_1442368_9EURO2_v2
- UP000000579_71421_HAEIN_v2
- UP000000429_85962_HELPY_v2
- UP000007841_1125630_KLEPH_v2
- UP000008153_5671_LEIIN_v2
- UP000078237_100816_9PEZI1_v2
- UP000000806_272631_MYCLE_v2 # 1,602
- UP000001584_83332_MYCTU_v2
- UP000020681_1299332_MYCUL_v2
- UP000000535_242231_NEIG1_v2
- UP000006304_1133849_9NOCA1_v2
- UP000024404_6282_ONCVO_v2
- UP000002059_502779_PARBA_v2
- UP000001450_36329_PLAF7_v2
- UP000002438_208964_PSEAE_v2
- UP000001014_99287_SALTY_v2
- UP000008854_6183_SCHMA_v2
- UP000002716_300267_SHIDS_v2
- UP000018087_1391915_SPOS1_v2
- UP000008816_93061_STAA8_v2
- UP000000586_171101_STRR6_v2
- UP000035681_6248_STRER_v2
- UP000030665_36087_TRITR_v2
- UP000008524_185431_TRYB2_v2
- UP000002296_353153_TRYCC_v2
- UP000270924_6293_WUCBA_v2
#- swissprot_pdb_v2
swissprot_pdb_v2_chunks:
- swissprot_pdb_v2_A0
- swissprot_pdb_v2_A1
- swissprot_pdb_v2_A2
- swissprot_pdb_v2_A3
- swissprot_pdb_v2_A4
- swissprot_pdb_v2_A5
- swissprot_pdb_v2_A6
- swissprot_pdb_v2_A7
- swissprot_pdb_v2_A8
- swissprot_pdb_v2_A9
- swissprot_pdb_v2_B0
- swissprot_pdb_v2_B1
- swissprot_pdb_v2_B2
- swissprot_pdb_v2_B3
- swissprot_pdb_v2_B4
- swissprot_pdb_v2_B5
- swissprot_pdb_v2_B6
- swissprot_pdb_v2_B7
- swissprot_pdb_v2_B8
- swissprot_pdb_v2_B9
- swissprot_pdb_v2_C0
- swissprot_pdb_v2_C1
- swissprot_pdb_v2_C2
- swissprot_pdb_v2_C3
- swissprot_pdb_v2_C4
- swissprot_pdb_v2_C5
- swissprot_pdb_v2_C6
- swissprot_pdb_v2_C7
- swissprot_pdb_v2_C8
- swissprot_pdb_v2_C9
- swissprot_pdb_v2_D0
- swissprot_pdb_v2_D1
- swissprot_pdb_v2_D2
- swissprot_pdb_v2_D3
- swissprot_pdb_v2_D4
- swissprot_pdb_v2_D5
- swissprot_pdb_v2_D6
- swissprot_pdb_v2_D7
- swissprot_pdb_v2_D8
- swissprot_pdb_v2_D9
- swissprot_pdb_v2_E0
- swissprot_pdb_v2_E1
- swissprot_pdb_v2_E2
- swissprot_pdb_v2_E3
- swissprot_pdb_v2_E4
- swissprot_pdb_v2_E5
- swissprot_pdb_v2_E6
- swissprot_pdb_v2_E7
- swissprot_pdb_v2_E8
- swissprot_pdb_v2_E9
- swissprot_pdb_v2_F0
- swissprot_pdb_v2_F1
- swissprot_pdb_v2_F2
- swissprot_pdb_v2_F3
- swissprot_pdb_v2_F4
- swissprot_pdb_v2_F5
- swissprot_pdb_v2_F6
- swissprot_pdb_v2_F7
- swissprot_pdb_v2_F8
- swissprot_pdb_v2_F9
- swissprot_pdb_v2_G0
- swissprot_pdb_v2_G1
- swissprot_pdb_v2_G2
- swissprot_pdb_v2_G3
- swissprot_pdb_v2_G4
- swissprot_pdb_v2_G5
- swissprot_pdb_v2_G7
- swissprot_pdb_v2_G8
- swissprot_pdb_v2_G9
- swissprot_pdb_v2_H0
- swissprot_pdb_v2_H1
- swissprot_pdb_v2_H2
- swissprot_pdb_v2_H3
- swissprot_pdb_v2_H5
- swissprot_pdb_v2_H6
- swissprot_pdb_v2_H7
- swissprot_pdb_v2_H8
- swissprot_pdb_v2_H9
- swissprot_pdb_v2_I0
- swissprot_pdb_v2_I1
- swissprot_pdb_v2_I2
- swissprot_pdb_v2_I3
- swissprot_pdb_v2_I4
- swissprot_pdb_v2_I6
- swissprot_pdb_v2_I7
- swissprot_pdb_v2_J3
- swissprot_pdb_v2_J4
- swissprot_pdb_v2_J5
- swissprot_pdb_v2_J7
- swissprot_pdb_v2_J9
- swissprot_pdb_v2_K0
- swissprot_pdb_v2_K2
- swissprot_pdb_v2_K3
- swissprot_pdb_v2_K4
- swissprot_pdb_v2_K5
- swissprot_pdb_v2_K6
- swissprot_pdb_v2_K7
- swissprot_pdb_v2_K8
- swissprot_pdb_v2_K9
- swissprot_pdb_v2_L0
- swissprot_pdb_v2_L5
- swissprot_pdb_v2_L7
- swissprot_pdb_v2_L8
- swissprot_pdb_v2_M0
- swissprot_pdb_v2_M1
- swissprot_pdb_v2_M2
- swissprot_pdb_v2_M3
- swissprot_pdb_v2_M4
- swissprot_pdb_v2_M5
- swissprot_pdb_v2_M7
- swissprot_pdb_v2_M9
- swissprot_pdb_v2_N0
- swissprot_pdb_v2_N1
- swissprot_pdb_v2_N4
- swissprot_pdb_v2_O0
- swissprot_pdb_v2_O1
- swissprot_pdb_v2_O2
- swissprot_pdb_v2_O3
- swissprot_pdb_v2_O4
- swissprot_pdb_v2_O5
- swissprot_pdb_v2_O6
- swissprot_pdb_v2_O7
- swissprot_pdb_v2_O8
- swissprot_pdb_v2_O9
- swissprot_pdb_v2_P0
- swissprot_pdb_v2_P1
- swissprot_pdb_v2_P2
- swissprot_pdb_v2_P3
- swissprot_pdb_v2_P4
- swissprot_pdb_v2_P5
- swissprot_pdb_v2_P6
- swissprot_pdb_v2_P7
- swissprot_pdb_v2_P8
- swissprot_pdb_v2_P9
- swissprot_pdb_v2_Q0
- swissprot_pdb_v2_Q1
- swissprot_pdb_v2_Q2
- swissprot_pdb_v2_Q3
- swissprot_pdb_v2_Q4
- swissprot_pdb_v2_Q5
- swissprot_pdb_v2_Q6
- swissprot_pdb_v2_Q7
- swissprot_pdb_v2_Q8
- swissprot_pdb_v2_Q9
- swissprot_pdb_v2_R0
- swissprot_pdb_v2_R1
- swissprot_pdb_v2_R4
- swissprot_pdb_v2_R8
- swissprot_pdb_v2_R9
- swissprot_pdb_v2_S0
- swissprot_pdb_v2_S2
- swissprot_pdb_v2_S3
- swissprot_pdb_v2_S4
- swissprot_pdb_v2_S5
- swissprot_pdb_v2_S6
- swissprot_pdb_v2_S7
- swissprot_pdb_v2_S8
- swissprot_pdb_v2_T0
- swissprot_pdb_v2_T1
- swissprot_pdb_v2_T2
- swissprot_pdb_v2_U2
- swissprot_pdb_v2_U3
- swissprot_pdb_v2_U4
- swissprot_pdb_v2_U5
- swissprot_pdb_v2_U6
- swissprot_pdb_v2_V3
- swissprot_pdb_v2_V5
- swissprot_pdb_v2_V6
- swissprot_pdb_v2_V9
- swissprot_pdb_v2_W0
- swissprot_pdb_v2_W1
- swissprot_pdb_v2_W2
- swissprot_pdb_v2_W3
- swissprot_pdb_v2_W4
- swissprot_pdb_v2_W5
- swissprot_pdb_v2_W6
- swissprot_pdb_v2_W7
- swissprot_pdb_v2_W8
- swissprot_pdb_v2_X1
- swissprot_pdb_v2_X2
- swissprot_pdb_v2_X4
- swissprot_pdb_v2_X5
- swissprot_pdb_v2_X6